config/routes.rb
Rails.application.routes.draw do
 root :to => 'homes#top'
 resources :books
  # For details on theedit DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new

  end

  def create
    @book = Book.new(book_params)
    if @book.save
     flash[:notice] = "Book was successfully created."
     redirect_to book_path(@book.id)
   else 
     @books = Book.all
     render :index
   end
  end

  def index
   @books =Book.all 
   @book = Book.new
  end

  def show
   @book = Book.find(params[:id])  
   
  end

  def edit
    @book = Book.find(params[:id])
    flash[:notice] = "Book was successfully updated."
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to "/books/#{@book.id}"
    else
      render :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id])  
    @book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to '/books'
  end
  
 private
 def book_params
  params.require(:book).permit(:title, :body)
 end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
 <div id= error>
  <div class= errortext><%= @book.errors.count %>error prohibited this book from being saved:</div>
 <ul>
   <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
 </ul>
 </div>
<% end %>


 <%= form_with model: @book do |f| %>
  <div class= "field">
  <label>
   <strong>Title</strong>
  </label>
   <%= f.text_field :title %>
 </div>
  
  <div class= "field">
  <label>
    <strong>Body</strong>
  </label>
    <%= f.text_field :body %>
  </div>
  
<div class= "action">
 <br> <%= f.submit 'Update Book' %>
</div> 

<br><%= link_to "show", "/books/#{@book.id}" %>
|
<%= link_to "back", "/books" %>

<% end %>

app/views/books/index.html.erb
<div class= "notice">
  <%= flash[:notice] %>
</div>

<div class= "head">
<h1>Books</h1>
</div>

<table>
  <thead>
    <tr>
     <th>Title</th>
     <th>Body</th>
     <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
<% @books.each do |book| %>
　<tr>
　  <td><%= book.title %></td>
　  <td><%= book.body %></td>
　　<td><%= link_to "Show", book_path(book) %></td>
    <td><%= link_to "Edit", edit_book_path(book) %></td>
    <td><%= link_to "Destroy", book_path(book), method: :delete, "data-confirm" => "Are you sure?" %></td>
　</tr>
<% end %>
</tbody>
</table>




<div class= "head">
<h2>New book</h2>
</div>

<% if @book.errors.any? %>
 <div id= error>
     <div class= errortext><%= @book.errors.count %>error prohibited this book from being saved:</div>
 <ul>
   <% @book.errors.full_messages.each do |message| %> 
    <li><%= message %></li>
   <% end %>
 </ul>
 </div>
<% end %>


<%= form_with model: @book, url: '/books', method: :post do |f| %>
 <div class= "field">
  <h4>Title</h4>
  <%= f.text_field :title %>
  </div>
  
  <div class= "field">
  <h4>Body</h4>
  <%= f.text_area :body%>
  </div>

   <br><%=  f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class= notice>
  <%= flash[:notice] %>
</div>


<p>
 <strong>Title:</strong>
 <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
 <%= @book.body %>
</p>
<%= link_to "Edit", edit_book_path(@book.id) %>
|
<%= link_to "Back", "/books" %>

app/views/homes/top.html.erb
<h1>
  ようこそ<strong>Bookers</strong>へ！
</h1>

<p>
  <strong> Bookers </strong>
  では、さまざまな書籍に関するあなたの意見や
</p>

<p>印象を共有し交換することができます</p>

<a href= "/books">start</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>